# Generated by Django 3.0.3 on 2020-03-31 02:36

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SysDomain',
            fields=[
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('status_cd', models.CharField(default='1000', max_length=4, verbose_name='状态')),
                ('domain_id', models.AutoField(primary_key=True, serialize=False, verbose_name='主题域标识')),
                ('domain_name', models.CharField(db_index=True, max_length=250, verbose_name='主题域名称')),
                ('domain_nbr', models.CharField(blank=True, max_length=30, null=True, verbose_name='主题域编码')),
                ('domain_desc', models.CharField(blank=True, max_length=250, null=True, verbose_name='主题域描述')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('par_domain', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='config.SysDomain', verbose_name='父级主题域标识')),
            ],
            options={
                'verbose_name': '主题域',
                'verbose_name_plural': '主题域',
                'db_table': 'sys_domain',
            },
        ),
        migrations.CreateModel(
            name='CommonRegion',
            fields=[
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('status_cd', models.CharField(default='1000', max_length=4, verbose_name='状态')),
                ('common_region_id', models.AutoField(primary_key=True, serialize=False, verbose_name='公共管理区域标识')),
                ('region_name', models.CharField(db_index=True, max_length=250, verbose_name='区域名称')),
                ('region_py_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='区域拼音名称')),
                ('region_nbr', models.CharField(blank=True, max_length=30, null=True, verbose_name='区域编码')),
                ('region_type', models.CharField(choices=[('1000', '国家'), ('1100', '省'), ('1200', '市'), ('1300', '区/县')], max_length=6, null=True, verbose_name='区域类型')),
                ('region_level', models.PositiveIntegerField(verbose_name='区域级别')),
                ('province_nbr', models.CharField(blank=True, max_length=32, null=True, verbose_name='省份编码')),
                ('remark', models.CharField(blank=True, max_length=250, null=True, verbose_name='备注')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('par_region', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='config.CommonRegion', verbose_name='上级区域标识')),
            ],
            options={
                'verbose_name': '公共管理区域',
                'verbose_name_plural': '公共管理区域',
                'db_table': 'common_region',
            },
        ),
    ]
