# Generated by Django 3.0.3 on 2020-03-31 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
    ]
