# Generated by Django 3.0.3 on 2020-03-31 03:48

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20200331_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysClass',
            fields=[
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('status_cd', models.CharField(default='1000', max_length=4, verbose_name='状态')),
                ('class_id', models.AutoField(primary_key=True, serialize=False, verbose_name='系统类标识')),
                ('class_name', models.CharField(db_index=True, max_length=30, verbose_name='类名')),
                ('table_code', models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='表英文名')),
                ('table_name', models.CharField(blank=True, db_index=True, max_length=250, null=True, verbose_name='表中文名')),
                ('domain', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.SysDomain', verbose_name='主题域')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
