# Generated by Django 3.0.3 on 2020-04-02 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_attrspec_attrvalue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attrvalue',
            options={'ordering': ['value_index'], 'verbose_name': '属性值', 'verbose_name_plural': '属性值'},
        ),
        migrations.AlterModelOptions(
            name='sysclass',
            options={'ordering': ['domain_id', 'class_id'], 'verbose_name': '系统类', 'verbose_name_plural': '系统类'},
        ),
        migrations.AlterField(
            model_name='attrspec',
            name='sys_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.SysClass', verbose_name='类'),
        ),
        migrations.AlterField(
            model_name='attrvalue',
            name='attr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.AttrSpec', verbose_name='属性'),
        ),
        migrations.AlterField(
            model_name='attrvalue',
            name='attr_value_name',
            field=models.CharField(db_index=True, default=1, max_length=30, verbose_name='属性值名称'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='sysclass',
            table='sys_class',
        ),
    ]
