# Generated by Django 3.0.3 on 2020-04-03 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_auto_20200402_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attrspec',
            name='attr_name',
            field=models.CharField(default=1, max_length=30, verbose_name='属性名称'),
            preserve_default=False,
        ),
    ]
